onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - '@prisma/engines'
  - better-sqlite3
  - prisma
patchedDependencies:
  nuxt-auth-utils: patches/nuxt-auth-utils.patch
