patchedDependencies:
  nuxt-auth-utils: patches/nuxt-auth-utils.patch
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  '@prisma/engines': true
  better-sqlite3: true
  prisma: true
minimumReleaseAgeExclude:
  - '@nuxt/image@2.1.0'
  - '@takumi-rs/core-darwin-arm64@2.5.3'
  - '@takumi-rs/core-darwin-x64@2.5.3'
  - '@takumi-rs/core-linux-arm64-gnu@2.5.3'
  - '@takumi-rs/core-linux-arm64-musl@2.5.3'
  - '@takumi-rs/core-linux-x64-gnu@2.5.3'
  - '@takumi-rs/core-linux-x64-musl@2.5.3'
  - '@takumi-rs/core-win32-arm64-msvc@2.5.3'
  - '@takumi-rs/core-win32-x64-msvc@2.5.3'
  - '@takumi-rs/core@2.5.3'
  - '@takumi-rs/helpers@2.5.3'
  - ipx@4.0.0-beta.1
  - '@tmlmt/cooklang-parser@3.0.0-alpha.44'
  - openai@7.1.0
