import { createRegex } from "human-regex";

export const pathRegex = new RegExp(
  createRegex()
    .startAnchor()
    .negativeLookahead("/")
    .startGroup()
    .anyOf("\\p{L}\\p{N}_ +%.-")
    .oneOrMore()
    .literal("/")
    .endGroup()
    .zeroOrMore()
    .anyOf("\\p{L}\\p{N}_ +%.-")
    .oneOrMore()
    .endAnchor()
    .toRegExp().source,
  "u",
);

export const urlRegex = createRegex()
  .startAnchor()
  .startGroup()
    .literal("http")
    .literal("s").optional()
    .literal("://")
  .endGroup().optional()
  .startGroup()
    .literal("www.")
  .endGroup().optional()
  .startNamedGroup("shortdomain")
    .startGroup()
      .startNamedGroup("subdomain")
        .anyOf("a-z0-9-")
        .oneOrMore()
      .endGroup()
      .literal(".")
    .endGroup().optional()
    .startNamedGroup("domain")
      .anyOf("a-z0-9-")
      .oneOrMore()
    .endGroup()
    .literal(".")
    .startGroup()
      .startNamedGroup("tld")
        .letter()
        .between(1, 63)
      .endGroup()
    .endGroup().optional()
  .endGroup()
  .startGroup()
    .literal(":")
    .startNamedGroup("port")
      .digit()
      .between(1, 5)
    .endGroup()
  .endGroup().optional().optional()
  .startGroup()
    .anyOf("\\/#")
    .startNamedGroup("path")
      .anyOf("\\w\\/\\-._~:\\/?#[\\]@!$&'()*+,;=.")
      .zeroOrMore()
    .endGroup().optional()
  .endGroup().optional()
  .endAnchor()
  .nonSensitive()
  .multiline()
  .toRegExp()

export const quantityWithOptionalUnitRegex = createRegex()
  .startNamedGroup("quantity")
    .notAnyOf("\\n\\r%").oneOrMore()
  .endGroup().optional()
  .startGroup()
    .literal("%")
    .startNamedGroup("unit")
      .notAnyOf("\\n\\r%").oneOrMore()
    .endGroup()
  .endGroup().optional()
  .toRegExp()
  
  export const rangeRegex = createRegex()
  .startAnchor()
  .digit().oneOrMore()
  .startGroup()
  .anyOf(".,/").exactly(1)
    .digit().oneOrMore()
  .endGroup().optional()
  .literal("-")
  .digit().oneOrMore()
  .startGroup()
    .anyOf(".,/").exactly(1)
    .digit().oneOrMore()
  .endGroup().optional()
  .endAnchor()
  .toRegExp()

  export const numberLikeRegex = createRegex()
  .startAnchor()
  .digit().oneOrMore()
  .startGroup()
    .anyOf(".,/").exactly(1)
    .digit().oneOrMore()
  .endGroup().optional()
  .endAnchor()
  .toRegExp()